
Server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: laundry_backend
    aop:
      proxy-target-class: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.66.69:3306/laundry_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Root@123
    druid:
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 10
      max-active: 200
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      pool-prepared-statements: true
      max-open-prepared-statements: 100

mybatis-plus:
  type-aliases-package: com.gtxyj.laundry_backend.*.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config:
    classpath: logback.xml

logging.level.org.springframework.baoot.autoconfigure: ERROR